#Reference: https://www.smarthomebeginner.com/docker-home-media-server-2018-basic
#Requirement: Set environmental variables: USERDIR, PUID, PGID, MYSQL_ROOT_PASSWORD, and TZ as explained in the reference.

version: "3.6"
services:

######### FRONTENDS ##########

 #Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    restart: always
    command: --templates http://templates/templates.json
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/gcsmount/docker/docker/portainer/data:/data
      - ~/gcsmount/docker/docker/shared:/shared
    environment:
      - TZ='Europe/London'

# Organizer - Unified HTPC/Home Server Web Interface
#  organizr:
#    container_name: organizr
#    hostname: organizr
#    restart: always
#    image: lsiocommunity/organizr
#    volumes:
#      - /docker/organizr:/config
#      - /docker/shared:/shared
#    ports:
#      - "8080:80"
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'

# WebUI for MariaDB
#  phpmyadmin:
#    hostname: phpmyadmin
#    container_name: phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    links:
#      - mariadb:db
#    ports:
#      - XXXX:80
#    environment:
#      - PMA_HOST=mariadb
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

######### DOCKER RELATED ##########

# Watchtower - Automatic Update of Containers/Apps
#  watchtower:
#    container_name: watchtower
#    hostname: watchtower
#    restart: always
#    image: v2tec/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --schedule "0 0 4 * * *" --cleanup

######### SMART HOME APPS ##########

# Home Assistant - Smart Home Hub
#  homeassistant:
#    container_name: homeassistant
#    hostname: hass
#    restart: always
#    image: homeassistant/home-assistant
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyACM0:/dev/ttyACM0
#    volumes:
#      - /docker/homeassistant:/config
#      - /etc/localtime:/etc/localtime:ro
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:8123"
#    privileged: true
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'

######### DOWNLOADERS ##########

# Transmission with VPN – Bittorrent Downloader
#  transmission-vpn:
#    container_name: transmission-vpn
#    hostname: transmission
#    image: haugene/transmission-openvpn
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - /dev/net/tun
#    restart: always
#    ports:
#    - "XXXX:9091"
#    dns:
#      - 1.1.1.1
#      - 1.0.0.1
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /docker/transmission-vpn:/data
#      - /docker/shared:/shared
#      - /Downloads:/data/watch
#      - /Downloads/completed:/data/completed
#      - /Downloads/incomplete:/data/incomplete
#    environment:
#      - OPENVPN_PROVIDER=IPVANISH
#      - OPENVPN_USERNAME=ipvanish_username
#      - OPENVPN_PASSWORD=ipvanish_password
#      - OPENVPN_CONFIG="YYYYYYYYYYY" 
#      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
#      - LOCAL_NETWORK=192.168.1.0/24
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'
#      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
#      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
#      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
#      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
#      - TRANSMISSION_UMASK=002
#      - TRANSMISSION_RATIO_LIMIT=0.01
#      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
#      - TRANSMISSION_ALT_SPEED_DOWN=2000
#      - TRANSMISSION_ALT_SPEED_ENABLED=true
#      - TRANSMISSION_ALT_SPEED_UP=15
#      - TRANSMISSION_SPEED_LIMIT_DOWN=6000
#      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
#      - TRANSMISSION_SPEED_LIMIT_UP=30
#      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
#      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
#      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
#      - TRANSMISSION_WATCH_DIR=/downloads
#      - TRANSMISSION_WATCH_DIR_ENABLED=true
#      - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed

# qBittorrent without VPN – Bittorrent Downloader (Alternative)
  qbittorrent:
    image: "linuxserver/qbittorrent"
    hostname: qbittorrent
    container_name: "qbittorrent"
    volumes:
      - ~/gcsmount/docker/docker/qbittorrent:/config
      - ~/gcsmount/docker/Downloads/completed:/downloads
      - ~/gcsmount/docker/docker/shared:/shared
    ports:
      - "8112:8112"
      - "6881:6881"
      - "6881:6881/udp"
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ='Europe/London'
      - UMASK_SET=002
      - WEBUI_PORT=8112

# SABnzbd – Usenet (NZB) Downloader
#  sabnzbd:
#    image: "linuxserver/sabnzbd"
#    hostname: sabnzbd
#    container_name: "sabnzbd"
#    volumes:
#      - /docker/sabnzbd:/config
#      - /Downloads/completed:/downloads
#      - /Downloads/incomplete:/incomplete-downloads
#      - /docker/shared:/shared
#    ports:
#        - "XXXX:8080"
#    restart: always
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'

# NZBGet – Usenet (NZB) Downloader (Alternative)
#  nzbget:
#    image: "linuxserver/nzbget"
#    hostname: nzbget
#    container_name: "nzbget"
#    volumes:
#      - /docker/sabnzbd:/config
#      - /Downloads:/downloads
#      - /Downloads/incomplete:/incomplete-downloads
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:6789"
#    restart: always
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'


######### PERSONAL VIDEO RECORDERS ##########

# Radarr – Movie Download and Management
  radarr:
    image: "linuxserver/radarr"
    hostname: radarr
    container_name: "radarr"
    volumes:
      - ~/gcsmount/docker/docker/radarr:/config
      - ~/gcsmount/docker/Downloads/completed:/downloads
      - ~/gcsmount/docker/media/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ~/gcsmount/docker/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ='Europe/London'

# CouchPotato – Movie Download and Management (Alternative)
#  couchpotato:
#    image: "linuxserver/couchpotato"
#    hostname: couchpotato
#    container_name: "couchpotato"
#    volumes:
#      - /docker/couchpotato:/config
#      - /Downloads/completed:/downloads"
#      - /media/movies:/movies"
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:5050"
#    restart: always
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - UMASK_SET=002
#      - TZ='Europe/London'

# Sonarr – TV Show Download and Management
  sonarr:
    image: "linuxserver/sonarr"
    hostname: sonarr
    container_name: "sonarr"
    volumes:
      - ~/gcsmount/docker/docker/sonarr:/config
      - ~/gcsmount/docker/Downloads/completed:/downloads
      - ~/gcsmount/docker/media/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ~/gcsmount/docker/docker/shared:/shared
    ports:
        - "8989:8989"
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ='Europe/London'

#LIDARR - Music Download and Management
#  lidarr:
#    image: "linuxserver/lidarr"
#    hostname: lidarr
#    container_name: "lidarr"
#    volumes:
#      - /docker/lidarr:/config
#      - /Downloads:/downloads
#      - /media/music:/music
#      - "/etc/localtime:/etc/localtime:ro"
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:8686"
#    restart: always
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'
      
# SickRage – TV Show Download and Management (Alternative)
#  sickrage:
#    image: "linuxserver/sickrage"
#    hostname: sickrage
#    container_name: "sickrage"
#    volumes:
#      - /docker/sickrage:/config
#      - /Downloads/completed:/downloads
#      - /media/tvshows:/tv
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:8081"
#    restart: always
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'

######### MEDIA SERVER APPS ##########

# Plex Media Server
#  plexms:
#    container_name: plexms
#    hostname: plexms
#    restart: always
#    image: plexinc/pms-docker
#    volumes:
#      - /docker/plexms:/config
#      - /Downloads/plex_tmp:/transcode
#      - /media/media:/media
#      - /docker/shared:/shared
#    ports:
#      - "32400:32400/tcp"
#      - "3005:3005/tcp"
#      - "8324:8324/tcp"
#      - "32469:32469/tcp"
#      - "1900:1900/udp"
#      - "32410:32410/udp"
#      - "32412:32412/udp"
#      - "32413:32413/udp"
#      - "32414:32414/udp"
#    environment:
#      - TZ='Europe/London'
#      - HOSTNAME="Docker Plex"
#      - PLEX_CLAIM="claim-YYYYYYYYY"
#      - PLEX_UID=1000
#      - PLEX_GID=1001
#      - ADVERTISE_IP="http://SERVER-IP:32400/"

# Tautulli (aka PlexPy) – Monitoring Plex Usage
#  tautulli:
#    container_name: tautulli
#    hostname: tautulli
#    restart: always
#    image: linuxserver/tautulli
#    volumes:
#      - /docker/tautulli/config:/config
#      - /docker/tautulli/logs:/logs:ro
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:8181"
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'  

# Ombi – Accept Requests for your Media Server
#  ombi:
#    container_name: ombi
#    hostname: ombi
#    restart: always
#    image: linuxserver/ombi
#    volumes:
#      - /docker/ombi:/config
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:3579"
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'

######### SEARCHERS ##########

# NZBHydra – NZB Meta Search
#  hydra:
#    image: "linuxserver/hydra"
#    hostname: hydra
#    container_name: "hydra"
#    volumes:
#      - /docker/hydra:/config
#      - /Downloads:/downloads
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:5075"
#    restart: always
#    environment:
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London' 

# Jackett – Torrent Proxy
  jackett:
    image: "linuxserver/jackett"
    hostname: jackett
    container_name: "jackett"
    volumes:
      - ~/gcsmount/docker/docker/jackett:/config
      - ~/gcsmount/docker/Downloads/completed:/downloads
      - "/etc/localtime:/etc/localtime:ro"
      - ~/gcsmount/docker/docker/shared:/shared
    ports:
      - "9117:9117"
    restart: always
    environment:
      - PUID=1000
      - PGID=1001
      - TZ='Europe/London'

######### UTILITIES ##########

# MariaDB – Database Server for your Apps
#  mariadb:
#    image: "linuxserver/mariadb"
#    container_name: "mariadb"
#    hostname: mariadb
#    volumes:
#        - /docker/mariadb:/config
#    ports:
#      - target: 3306
#        published: 3306
#        protocol: tcp
#        mode: host
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - PUID=1000
#      - PGID=1001
#      - TZ='Europe/London'

# NextCloud – Your Own Cloud Storage
#  nextcloud:
#    container_name: nextcloud
#    hostname: nextcloud
#    restart: always
#    image: linuxserver/nextcloud
#    volumes:
#      - /docker/nextcloud:/config
#      - /shared_data:/data
#      - /docker/shared:/shared
#    ports:
#      - "XXXX:443"
#    environment:
#      - PUID=1000
#      - PGID=1001
